f

diff --git a/.github/workflows/translate-issues.yml b/.github/workflows/translate-issues.yml
--- a/.github/workflows/translate-issues.yml
+++ b/.github/workflows/translate-issues.yml
@@ -40,22 +40,22 @@ jobs:
             echo "OPENAI_API_KEY is set"
           fi
 
-      # - name: Test OpenAI API Connectivity
-      #   run: |
-      #     for i in {1..3}; do
-      #       response=$(curl -X POST https://api.openai.com/v1/chat/completions \
-      #       -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
-      #       -H "Content-Type: application/json" \
-      #       -d '{"model":"gpt-4o-mini","messages":[{"role":"user","content":"Hello"}]}' \
-      #       --http1.1 -v -i)
-      #       echo "$response"
-      #       # Check if response contains any error
-      #       if [[ "$response" == *"error"* ]]; then
-      #         echo "Error occurred during API call"
-      #         exit 1
-      #       fi
-      #       break
-      #     done
+      - name: Test OpenAI API Connectivity
+        run: |
+          for i in {1..3}; do
+            response=$(curl -X POST https://api.openai.com/v1/chat/completions \
+            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
+            -H "Content-Type: application/json" \
+            -d '{"model":"gpt-4o-mini","messages":[{"role":"user","content":"Hello"}]}' \
+            --http1.1 -v -i)
+            echo "$response"
+            # Check if response contains any error
+            if [[ "$response" == *"error"* ]]; then
+              echo "Error occurred during API call"
+              exit 1
+            fi
+            break
+          done
         
 
       - name: Translate Issues
